./run.sh: 12: ./run.sh: let: not found
Traceback (most recent call last):
  File "group_nodes.py", line 12, in <module>
    cores = int(sys.argv[3])
IndexError: list index out of range
i {1..10}  P 4 ppn 1 d 16
i {1..10}  P 4 ppn 1 d 256
i {1..10}  P 4 ppn 1 d 2048
./run.sh: 12: ./run.sh: let: not found
Traceback (most recent call last):
  File "group_nodes.py", line 12, in <module>
    cores = int(sys.argv[3])
IndexError: list index out of range
i {1..10}  P 4 ppn 8 d 16
i {1..10}  P 4 ppn 8 d 256
i {1..10}  P 4 ppn 8 d 2048
./run.sh: 12: ./run.sh: let: not found
Traceback (most recent call last):
  File "group_nodes.py", line 12, in <module>
    cores = int(sys.argv[3])
IndexError: list index out of range
i {1..10}  P 16 ppn 1 d 16
i {1..10}  P 16 ppn 1 d 256
./run.sh: 12: ./run.sh: let: not found
Traceback (most recent call last):
  File "group_nodes.py", line 12, in <module>
    cores = int(sys.argv[3])
IndexError: list index out of range
i {1..10}  P 4 ppn 1 d 16
i {1..10}  P 4 ppn 1 d 256
i {1..10}  P 4 ppn 1 d 2048
i {1..10}  P 16 ppn 1 d 2048
./run.sh: 12: ./run.sh: let: not found
Traceback (most recent call last):
  File "group_nodes.py", line 12, in <module>
    cores = int(sys.argv[3])
IndexError: list index out of range
i {1..10}  P 16 ppn 8 d 16
i {1..10}  P 16 ppn 8 d 256
i {1..10}  P 16 ppn 8 d 2048
